### ISSUE TITLE
怎样用 nginx 反向代理？

### ISSUE THREAD

**Issue by ywzhaiqi** [lafjs/laf#32]
我的轻量云用 nginx 反向代理了其它多个服务，现在我想把下面域名给 laf。

下面这样尝试无法访问
```
server {  
    listen 80;
    server_name laf.domain.com;

    location / {
        proxy_set_header   X-Real-IP $remote_addr;
        proxy_set_header   Host      $http_host;
        proxy_pass         http://local-dev.host:8020;
    }
}

server {  
    listen 80;
    server_name console.laf.domain.com;

    location / {
        proxy_set_header   X-Real-IP $remote_addr;
        proxy_set_header   Host      $http_host;
        proxy_pass         http://console.local-dev.host:8020;
    }
}
```

**Comment by ywzhaiqi** [comment]
不好意思，好像可以了。
把 `proxy_pass         http://local-dev.host:8020;` 改成 `proxy_pass         http://localhost:8020;`

**Comment by maslow** [comment]
这个场景，我倒没试过。 
你可以先看看 gateway 中的 几个 nginx conf 文件，还是有一些转发规则要注意的：

**Comment by maslow** [comment]
packages/gateway/:
 - app.conf
 - system.conf
 - fs-proxy.conf

**Comment by maslow** [comment]
1. 每个 laf app 会分配一个 独立二级域名， 所以 app.conf 中 server_name 用的是泛解析： *.local-dev.host； 你前置的 nginx 也要把这条规则给转发给 laf gateway;

**Comment by maslow** [comment]
> 1. 每个 laf app 会分配一个 独立二级域名， 所以 app.conf 中 server_name 用的是泛解析： *.local-dev.host； 你前置的 nginx 也要把这条规则给转发给 laf gateway;

在你的前置 nginx 中 可以直接 把 *.yourdomain.com  全部转发给 laf gateway

**Comment by maslow** [comment]
2. 每个 文件 bucket 也会分配一个 独立二级域名，默认用的是 *.fs.yourdomain.com， 我不清楚你转发 *.domain.com 能不能覆盖这种情况，如果不行 还要在 你的前置 nginx 中再增加 一条转发规则 *.fs.yourdomain.com 到 laf gateway；

**Comment by maslow** [comment]
3. laf app 是支持 websocket 的， 在 gateway/app.conf 中有体现， 这条也要同步转发；

**Comment by maslow** [comment]
laf 的定位是个云开发平台， 会有多个应用，虽然当前给的文档是单机部署， 后期主要针对的是 集群部署(k8s)，
所以 这种 旧有应用与 laf 共用服务器的场景 不是首先考虑的范畴， 部署起来 要麻烦一些。 

建议 加 readme 里的 qq 群， 我们可以更快捷的交流

**Comment by ywzhaiqi** [comment]
好的，感谢

**Comment by ywzhaiqi** [comment]
经过反复测试，最终搞定了。

`.env`  配置
```
DEPLOY_DOMAIN=AAA.XXXX.com
SYS_CLIENT_HOST=console.AAA.XXXX.com
```

nginx 配置
```
map $http_upgrade $connection_upgrade {
    default upgrade;
    '' close;
}

upstream backend {
    server localhost:8080;
}

server {
    listen 80;
    server_name AAA.XXXX.com *.AAA.XXXX.com;

    location / {
        proxy_pass       http://backend;
        proxy_set_header Host $host:$server_port;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Real-PORT $remote_port;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $connection_upgrade;
    }
}

server {  
    listen 80;
    server_name console.AAA.XXXX.com;

    location / {
        proxy_pass         http://console.local-dev.host:8080;
        proxy_set_header Host $host:$server_port;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Real-PORT $remote_port;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}
```

**Comment by geekape** [comment]
> 经过反复测试，最终搞定了。
> 
> `.env` 配置
> 
> ```
> DEPLOY_DOMAIN=AAA.XXXX.com
> SYS_CLIENT_HOST=console.AAA.XXXX.com
> ```
> 
> nginx 配置
> 
> ```
> map $http_upgrade $connection_upgrade {
>     default upgrade;
>     '' close;
> }
> 
> upstream backend {
>     server localhost:8080;
> }
> 
> server {
>     listen 80;
>     server_name AAA.XXXX.com *.AAA.XXXX.com;
> 
>     location / {
>         proxy_pass       http://backend;
>         proxy_set_header Host $host:$server_port;
>         proxy_set_header X-Real-IP $remote_addr;
>         proxy_set_header X-Real-PORT $remote_port;
>         proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
> 
>         proxy_http_version 1.1;
>         proxy_set_header Upgrade $http_upgrade;
>         proxy_set_header Connection $connection_upgrade;
>     }
> }
> ```

感谢
