### ISSUE TITLE
app-console: 云存储支持 service account 管理

### ISSUE THREAD

**Issue by maslow** [lafjs/laf#76]
laf 提供完整的 minio 能力，可将 laf oss bucket 用于其它 minio/s3 兼容的场景，
所以需要提供 app oss 的 Service Account 能力；

- 一个应用仅支持生成一个 SA
- SA 只在生成时显示一次，不可重复查看
- 重新生成 SA 即为重置，会删除之前存在的 SA

> 只需要提供一个「获取SA」 按钮和接口即可，即重置。

同时增加显示 endpoint；

**Comment by dingzhenznen** [comment]
# service account

## 介绍
  生成，重置sa。

### sa设计思路
**1.文档对象设计**
* 应用service account对象(service_account)
  字段|类型|说明
  --|:--:|--:
  _id|string|主键|
  status|string|状态
  appid|string|应用ID
  access_key|string|目标应用ID
  secret_key|string|目标应用ID
  created_at|Date|创建时间
  updated_at|Date|更新时间
* status取值说明
  ```
    1.使用中
    2.删除
    ```
**2.接口设计**
* 更新sa(PUT /bucket/serviceAccount)
  ```
   1.请求参数
   {
   }
   2.响应
   {
    "code":0,
    "data":{"access_key":"","secret_key":""}
  }
  ```
